runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images
  static_dir: images
  secure: always

- url: /menus
  static_dir: menus
  secure: always

- url: /style.css
  static_files: style.css
  upload: style.css
  secure: always

- url: /
  script: main.app
  secure: always

- url: /mission
  script: main.app
  secure: always

- url: /contact
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: endpoints
  version: latest
